/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    OnlinePlayersCard: typeof import('./src/components/OnlinePlayersCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerConsoleCard: typeof import('./src/components/ServerConsoleCard.vue')['default']
    ServerStatusCard: typeof import('./src/components/ServerStatusCard.vue')['default']
    SkillsLeaderboardCard: typeof import('./src/components/SkillsLeaderboardCard.vue')['default']
    ToastNotifications: typeof import('./src/components/ToastNotifications.vue')['default']
  }
}
