/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppNavigation: typeof import('./src/components/AppNavigation.vue')['default']
    BlockAnalyticsTab: typeof import('./src/components/insights/BlockAnalyticsTab.vue')['default']
    BlockIcon: typeof import('./src/components/BlockIcon.vue')['default']
    OnlinePlayersCard: typeof import('./src/components/index/OnlinePlayersCard.vue')['default']
    OverviewTab: typeof import('./src/components/insights/OverviewTab.vue')['default']
    PlayerAnalyticsTab: typeof import('./src/components/insights/PlayerAnalyticsTab.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerConsoleCard: typeof import('./src/components/index/ServerConsoleCard.vue')['default']
    ServerStatusCard: typeof import('./src/components/index/ServerStatusCard.vue')['default']
    SessionAnalyticsCharts: typeof import('./src/components/sessions/SessionAnalyticsCharts.vue')['default']
    SessionFilters: typeof import('./src/components/sessions/SessionFilters.vue')['default']
    SessionPageHeader: typeof import('./src/components/sessions/SessionPageHeader.vue')['default']
    SessionsTable: typeof import('./src/components/sessions/SessionsTable.vue')['default']
    SessionStatisticsCards: typeof import('./src/components/sessions/SessionStatisticsCards.vue')['default']
    SkillsLeaderboardCard: typeof import('./src/components/index/SkillsLeaderboardCard.vue')['default']
    ToastNotifications: typeof import('./src/components/ToastNotifications.vue')['default']
  }
}
